apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-backend
  namespace: personal-dashboard
  labels:
    app: dashboard-backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard-backend
  template:
    metadata:
      labels:
        app: dashboard-backend
        version: v1
    spec:
      containers:
      - name: dashboard-backend
        image: dashboard-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: personal-dashboard
  labels:
    app: dashboard-backend
spec:
  selector:
    app: dashboard-backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP