apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-frontend
  namespace: personal-dashboard
  labels:
    app: dashboard-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dashboard-frontend
  template:
    metadata:
      labels:
        app: dashboard-frontend
    spec:
      containers:
      - name: dashboard-frontend
        image: 339712892906.dkr.ecr.us-east-1.amazonaws.com/personal-dashboard-frontend:latest  # Replace with your ECR frontend URL
        imagePullPolicy: Always
        
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: personal-dashboard
spec:
  selector:
    app: dashboard-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP